In [2]:
import numpy as np

In [4]:
arr=[1,2,3,4,5]

In [5]:
print(type(arr))

<class 'list'>


In [6]:
print(arr)

[1, 2, 3, 4, 5]


In [7]:
a=np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)


<class 'numpy.ndarray'>
(5,)
int32
1


In [8]:
b=np.array([[1,2,3], [4,5,6]])
print(b)
print(b.ndim)
b.shape

[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [9]:
arr=[6,7,8,9]
print(type(arr))
a=np.array(arr)
print(a.shape)
print(a.dtype)
print(a.ndim)
b=np.array([[1,2,3], [4,5,6]])
print(b)
print(b.ndim)
b.shape

<class 'list'>
(4,)
int32
1
[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [12]:
array=np.random.random((2,3))
print(array)

[[0.97884467 0.65245889 0.97528206]
 [0.53703449 0.12014063 0.60193554]]


In [3]:
array=np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
c=np.array([[9.0,8.0,7.0], [1.0,2.0,3.0]])
d=np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])

In [5]:
c+d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [6]:
c-d

array([[ 5.,  3.,  1.],
       [-8., -6., -4.]])

In [7]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [8]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [9]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [10]:
import pandas as pd


In [11]:
days=pd.Series(['monday','tuesday','wednesday'])

In [12]:
print(days)

0       monday
1      tuesday
2    wednesday
dtype: object


In [15]:
daylist=np.array(['Monday','Tuesday','Wednesday'])

In [16]:
numpy_days=pd.Series(daylist)
print(numpy_days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [17]:
days=pd.Series(['monday','tuesday','wednesday'],index=['a','b','c'])

In [19]:
days1=pd.Series({'a':'monday','b':'tuesday','d':'wednesday'})

In [20]:
print(days)
print(days1)

a       monday
b      tuesday
c    wednesday
dtype: object
a       monday
b      tuesday
d    wednesday
dtype: object


In [21]:
days[0]

'monday'

In [22]:
days['c']

'wednesday'

In [23]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [44]:
df_dict={'Country':['USA','UK','South Korea'],
        'Capital':['Washington','London','Seoul'],
        'Population':[10,100,200]}

In [45]:
print(df_dict)

{'Country': ['USA', 'UK', 'South Korea'], 'Capital': ['Washington', 'London', 'Seoul'], 'Population': [10, 100, 200]}


In [46]:
df=pd.DataFrame(df_dict, index=[1, 2, 3])

In [47]:
print(df)

       Country     Capital  Population
1          USA  Washington          10
2           UK      London         100
3  South Korea       Seoul         200


In [48]:
df.iloc[2]

Country       South Korea
Capital             Seoul
Population            200
Name: 3, dtype: object

In [49]:
df.loc[2]

Country           UK
Capital       London
Population       100
Name: 2, dtype: object

In [50]:
df['Population']

1     10
2    100
3    200
Name: Population, dtype: int64

In [51]:
df.at[2,'Country']

'UK'

In [52]:
df.iat[2,0]

'South Korea'

In [53]:
df['Population'].sum()

310

In [54]:
df.mean()

C:\Users\PRAGAT~1\AppData\Local\Temp/ipykernel_6948/3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


Population    103.333333
dtype: float64

In [55]:
df.describe()

Population
count    3.000000
mean   103.333333
std     95.043850
min     10.000000
25%     55.000000
50%    100.000000
75%    150.000000
max    200.000000

In [59]:
df_dict2={'Name':['Bella','Caro','JK',np.nan],
'Profession':['Developer','Engineer','Idol','Actor'],
         'Experience':[4,np.nan,10,1],
         'Height':[160,162,168,np.nan]}
new_df=pd.DataFrame(df_dict2, index=[1,2,3,4])

In [60]:
print(new_df)

    Name Profession  Experience  Height
1  Bella  Developer         4.0   160.0
2   Caro   Engineer         NaN   162.0
3     JK       Idol        10.0   168.0
4    NaN      Actor         1.0     NaN


In [61]:
new_df.isnull()

Name  Profession  Experience  Height
1  False       False       False   False
2  False       False        True   False
3  False       False       False   False
4   True       False       False    True

In [63]:
new_df.dropna()

Name Profession  Experience  Height
1  Bella  Developer         4.0   160.0
3     JK       Idol        10.0   168.0